### ISSUE TITLE
/getmedia search query case sensitive

### ISSUE THREAD

**Issue by a-knaw-knee-mus** [eldossjogy/MediaLibrary#1]
Hello Eldoss, been using our bot for a while now and it's not bad! However, I'm trying to use the /getmedia slash command but it is rather cumbersome that the search query must be case-sensitive. Would it be possible to make it case insensitive 🤔?

**Comment by eldossjogy** [comment]
Thanks for the suggestion. In the future, I will update the /getmedia to show the most matching media name and ask the user if that is what they meant. This would resolve the problem of case-sensitive and names with spaces.

**Comment by a-knaw-knee-mus** [comment]
🥳
